[package]
name = "vk-archive-parser"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "1.0.2"
chrono = "0.4.26"
rayon = "1.7.0"
tl = { version = "0.7.7", features = ["simd"] }

[profile.release]
debug = true
